spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postal
    username: postal
    password: postal
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

app:
  queues:
    letter: letter.queue
    parcel: parcel.queue

