spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postal
    username: postal
    password: postal
  jpa:
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: localhost
    port: 5672
app:
  queues:
    parcel: parcel.queue
